language: r
cache: packages
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - drat
  - units

before_install:
  - tlmgr install fancyvrb units

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
